# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4f60\u7684\u540d\u5b57')),
                ('email', models.CharField(max_length=30, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('adress', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('website', models.CharField(max_length=100, verbose_name='\u7f51\u5740')),
                ('what_do_you_want', models.CharField(max_length=30, verbose_name='\u7ea6\u4ec0\u4e48\uff1f')),
                ('content', models.TextField(verbose_name='\u5177\u4f53\u6d88\u606f')),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211',
                'verbose_name_plural': '\u8054\u7cfb\u6211',
            },
        ),
    ]
