# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-18 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='image/default_article.png', upload_to='image/%Y/%m', verbose_name='\u6587\u7ae0\u914d\u56fe')),
                ('title', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('introduce', models.TextField(verbose_name='\u6587\u7ae0\u7b80\u4ecb')),
                ('tag1', models.CharField(default='\u751f\u6d3b', max_length=10, verbose_name='\u6807\u7b7e1')),
                ('tag2', models.CharField(default='\u968f\u7b14', max_length=10, verbose_name='\u6807\u7b7e2')),
                ('tag3', models.CharField(default='\u64cd\u86cb', max_length=10, verbose_name='\u6807\u7b7e3')),
                ('tag4', models.CharField(default='\u73a9\u610f\u513f', max_length=10, verbose_name='\u6807\u7b7e4')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('creat_data', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u7ba1\u7406',
                'verbose_name_plural': '\u535a\u5ba2\u7ba1\u7406',
            },
        ),
    ]
