# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-18 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creat_data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
