# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-18 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='image/default.png', max_length=200, upload_to='image/%Y/%m')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.CharField(max_length=50, verbose_name='\u5185\u5bb9\u7b80\u4ecb')),
                ('create_data', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u7167\u7247',
                'verbose_name_plural': '\u7167\u7247',
            },
        ),
    ]
