# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-19 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170819_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='image/default.png', max_length=200, upload_to='image/%Y/%m'),
        ),
    ]
